### PR TITLE
Send Error Email

### LINKED ISSUE #88: Error notifications
When an automatic import or specific group of records fails in that import, I would like to be able to access the information. 

For example, 100 contract/grant records are sent at one time. If a record in the batch fails, all 100 records fail. If this happens, Nicole and the team need to know what records failed so we can either update them manually or verify the data.

### PR DESCRIPTION
**Pull request by memsdm05**
Fixes #88

### CODE REVIEW

File: app/importers/osp_data/osp_importer.rb [hunk 1]
```diff
@@ -33,7 +33,7 @@ def format_and_populate
   private
 
   def is_good_date(row)
-    if row['submitted'].blank? && row['awarded'].present?
+    if (row['submitted'].blank? || row['submitted'] == '/  /') && row['awarded'].present?
```
Comment (ajkiessl) [inline app/importers/osp_data/osp_importer.rb:36]: Do we still need to do this?  I thought we determined the `.format_date_fields` method below converts the '/   /'s to blanks.

File: spec/mailers/previews/error_preview.rb [hunk 2]
```diff
@@ -0,0 +1,3 @@
+# Preview all emails at http://localhost:3000/rails/mailers/error
+class ErrorPreview < ActionMailer::Preview
```
Comment (ajkiessl) [inline spec/mailers/previews/error_preview.rb:2]: Can this be removed?

File: app/jobs/application_job.rb [hunk 3]
```diff
@@ -18,15 +18,29 @@ def clean_up
...
+        error_logger.error "Affected Faculty: #{error[:affected_faculty]}" if error[:affected_faculty]
+        error_logger.error "Affected OSPs: #{error[:affected_osps]}" if error[:affected_osps]
+      end
+    rescue StandardError => e
+      has_error = true
+      error_logger.error "Thrown Error: #{e.message}"
+      error_logger.error e.backtrace.join("\n")
+      raise # we still want to handle the error elsewhere
+    ensure
+      ErrorMailer.error_email(name, log_path).deliver_now if has_error
```
Comment (ajkiessl) [inline app/jobs/application_job.rb:43]: Do you think we could add a test for the new error handling somewhere?  I think https://github.com/psu-libraries/fams_tools/blob/main/spec/jobs/application_job_spec.rb would be the place for this.

**Review by ajkiessl — CHANGES_REQUESTED** [review]
A couple questions/requests below.

File: spec/mailers/previews/error_preview.rb (hunk 2 above)
Comment (memsdm05) [reply spec/mailers/previews/error_preview.rb:2]: This was autogenerated when I created the new mailer. I don't think it does anything but I'll remove it anyway.

File: app/importers/osp_data/osp_importer.rb (hunk 1 above)
Comment (memsdm05) [reply app/importers/osp_data/osp_importer.rb:36]: I remember it being finicky but I think it was due to excel formatting dates. Ill revert this one.

File: spec/jobs/application_job_spec.rb [hunk 4]
```diff
@@ -18,10 +18,11 @@
 
     it 'changes integration is_active to true' do
       # This is a hacky way of testing the start
-      allow_any_instance_of(OspIntegrateJob).to receive(:perform).and_raise StandardError
+      error = StandardError.new('Test error')
+      allow_any_instance_of(OspIntegrateJob).to receive(:integrate).and_raise error
       allow_any_instance_of(OspIntegrateJob).to receive(:clean_up).and_return true
       expect { OspIntegrateJob.perform_now(params, '/log/path') }.to raise_error StandardError
-      expect(Integration.running?).to eq true
+      expect(ActionMailer::Base.deliveries.count).to eq(1)
```
Comment (ajkiessl) [inline spec/jobs/application_job_spec.rb:25]: It seems like this test is no longer testing what it claims to be testing.  We can either delete it, or try to get it to test the integration being set to is_active.  I'm assuming this test was set up to "hack" the integration to keep it `.running? == true`, but now that we catch errors, it doesn't work?

Comment (memsdm05) [reply spec/jobs/application_job_spec.rb:25]: All errors are still passed down due to the raise function. The difference is I also log/email them now. Given this info, I think it still tests what it needs to despite the hacky nature.

**Review by ajkiessl — APPROVED** [review]
